// <auto-generated />
using System;
using LogHub.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogHub.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230722223209_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogHub.Domain.Entities.Actions.RecordAction<LogHub.Domain.Entities.Bases.BaseActionId, LogHub.Domain.Entities.Bases.BaseId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("RecordId");

                    b.ToTable("BaseActions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Actions.RecordAction<LogHub.Domain.Entities.Docs.DocActionId, LogHub.Domain.Entities.Docs.DocumentId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("RecordId");

                    b.ToTable("DocActions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Actions.RecordAction<LogHub.Domain.Entities.Logbooks.LogbookActionId, LogHub.Domain.Entities.Logbooks.LogbookId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("RecordId");

                    b.ToTable("LogbookActions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Bases.Base", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Bases");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Bases.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlanTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("DataManagementPlanTemplates");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DataManagementPlanTemplate");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DataManagementPlanTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DmpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DataManagementPlanTemplateId");

                    b.HasIndex("DmpId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.DocEditor", b =>
                {
                    b.Property<Guid>("DocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DocEditors");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.DocLabel", b =>
                {
                    b.Property<Guid>("DocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocId", "LabelId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("LabelId");

                    b.ToTable("DocLabels");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LogbookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LogbookId");

                    b.ToTable("Docs");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.FavouriteDoc", b =>
                {
                    b.Property<Guid>("DocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FavouriteDocs");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Logbooks.Logbook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.ToTable("Logbooks", (string)null);
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Organisations.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Permissions.RecordPermission<LogHub.Domain.Entities.Bases.BasePermissionId, LogHub.Domain.Entities.Bases.BaseId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.HasIndex("RecordId");

                    b.HasIndex("UserId");

                    b.ToTable("BasePermissions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Permissions.RecordPermission<LogHub.Domain.Entities.Docs.DocPermissionId, LogHub.Domain.Entities.Docs.DocumentId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("RecordId");

                    b.HasIndex("UserId");

                    b.ToTable("DocPermissions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Permissions.RecordPermission<LogHub.Domain.Entities.Logbooks.LogbookPermissionId, LogHub.Domain.Entities.Logbooks.LogbookId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid?>("LogbookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LogbookId");

                    b.HasIndex("RecordId");

                    b.HasIndex("UserId");

                    b.ToTable("LogbookPermissions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Requests.RecordRequest<LogHub.Domain.Entities.Bases.BaseRequestId, LogHub.Domain.Entities.Bases.BaseId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HandlerId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("RecordId");

                    b.ToTable("BaseRequests");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Requests.RecordRequest<LogHub.Domain.Entities.Docs.DocRequestId, LogHub.Domain.Entities.Docs.DocumentId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HandlerId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("RecordId");

                    b.ToTable("DocRequests");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Requests.RecordRequest<LogHub.Domain.Entities.Logbooks.LogbookRequestId, LogHub.Domain.Entities.Logbooks.LogbookId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HandlerId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("RecordId");

                    b.ToTable("LogbookRequests");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orcid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlan", b =>
                {
                    b.HasBaseType("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlanTemplate");

                    b.HasDiscriminator().HasValue("DataManagementPlan");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Actions.RecordAction<LogHub.Domain.Entities.Bases.BaseActionId, LogHub.Domain.Entities.Bases.BaseId>", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Bases.Base", null)
                        .WithMany("Actions")
                        .HasForeignKey("RecordId");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Actions.RecordAction<LogHub.Domain.Entities.Docs.DocActionId, LogHub.Domain.Entities.Docs.DocumentId>", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Docs.Document", null)
                        .WithMany("Actions")
                        .HasForeignKey("RecordId");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Actions.RecordAction<LogHub.Domain.Entities.Logbooks.LogbookActionId, LogHub.Domain.Entities.Logbooks.LogbookId>", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Logbooks.Logbook", null)
                        .WithMany("Actions")
                        .HasForeignKey("RecordId");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Bases.Base", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Bases.Label", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Bases.Base", null)
                        .WithMany("Labels")
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlanTemplate", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("LogHub.Domain.Entities.Organisations.Organisation", null)
                        .WithMany("DataManagementPlanTemplates")
                        .HasForeignKey("OrganisationId");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.Question", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlanTemplate", null)
                        .WithMany("Questions")
                        .HasForeignKey("DataManagementPlanTemplateId");

                    b.HasOne("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlanTemplate", null)
                        .WithMany()
                        .HasForeignKey("DmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.DocEditor", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Docs.Document", null)
                        .WithMany("Editors")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.DocLabel", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Docs.Document", null)
                        .WithMany("Labels")
                        .HasForeignKey("DocumentId");

                    b.HasOne("LogHub.Domain.Entities.Bases.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.Document", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Logbooks.Logbook", null)
                        .WithMany()
                        .HasForeignKey("LogbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.FavouriteDoc", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Docs.Document", null)
                        .WithMany()
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany("FavouriteDocs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Logbooks.Logbook", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Bases.Base", null)
                        .WithMany()
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Organisations.Department", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Organisations.Organisation", null)
                        .WithMany("Departments")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Permissions.RecordPermission<LogHub.Domain.Entities.Bases.BasePermissionId, LogHub.Domain.Entities.Bases.BaseId>", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Bases.Base", null)
                        .WithMany("Permissions")
                        .HasForeignKey("BaseId");

                    b.HasOne("LogHub.Domain.Entities.Bases.Base", null)
                        .WithMany()
                        .HasForeignKey("RecordId");

                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Permissions.RecordPermission<LogHub.Domain.Entities.Docs.DocPermissionId, LogHub.Domain.Entities.Docs.DocumentId>", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Docs.Document", null)
                        .WithMany("Permissions")
                        .HasForeignKey("DocumentId");

                    b.HasOne("LogHub.Domain.Entities.Docs.Document", null)
                        .WithMany()
                        .HasForeignKey("RecordId");

                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Permissions.RecordPermission<LogHub.Domain.Entities.Logbooks.LogbookPermissionId, LogHub.Domain.Entities.Logbooks.LogbookId>", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Logbooks.Logbook", null)
                        .WithMany("Permissions")
                        .HasForeignKey("LogbookId");

                    b.HasOne("LogHub.Domain.Entities.Logbooks.Logbook", null)
                        .WithMany()
                        .HasForeignKey("RecordId");

                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Requests.RecordRequest<LogHub.Domain.Entities.Bases.BaseRequestId, LogHub.Domain.Entities.Bases.BaseId>", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Bases.Base", null)
                        .WithMany("Requests")
                        .HasForeignKey("RecordId");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Requests.RecordRequest<LogHub.Domain.Entities.Docs.DocRequestId, LogHub.Domain.Entities.Docs.DocumentId>", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Docs.Document", null)
                        .WithMany("Requests")
                        .HasForeignKey("RecordId");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Requests.RecordRequest<LogHub.Domain.Entities.Logbooks.LogbookRequestId, LogHub.Domain.Entities.Logbooks.LogbookId>", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Logbooks.Logbook", null)
                        .WithMany("Requests")
                        .HasForeignKey("RecordId");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Organisations.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("LogHub.Domain.Entities.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogHub.Domain.Entities.Users.UserSetting", "UserSetting", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AutoSave")
                                .HasColumnType("bit");

                            b1.Property<bool>("EmailNotification")
                                .HasColumnType("bit");

                            b1.Property<int>("FontSize")
                                .HasColumnType("int");

                            b1.Property<int>("Theme")
                                .HasColumnType("int");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("UserSetting")
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Bases.Base", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Labels");

                    b.Navigation("Permissions");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlanTemplate", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.Document", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Editors");

                    b.Navigation("Labels");

                    b.Navigation("Permissions");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Logbooks.Logbook", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Permissions");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.Navigation("DataManagementPlanTemplates");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("FavouriteDocs");
                });
#pragma warning restore 612, 618
        }
    }
}
