// <auto-generated />
using System;
using LogHub.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogHub.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogHub.Domain.Entities.Actions.RecordAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("RecordId");

                    b.ToTable("RecordActions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Bases.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DataManagementPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DataManagementPlanId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.DocEditor", b =>
                {
                    b.Property<Guid>("DocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocId", "UserId");

                    b.ToTable("DocEditors");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.DocLabel", b =>
                {
                    b.Property<Guid>("DocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocId", "LabelId");

                    b.ToTable("DocLabels");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.FavouriteDoc", b =>
                {
                    b.Property<Guid>("DocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FavouriteDocs");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Organisations.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Permissions.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.HasIndex("UserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Requests.RecordRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HandlerId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("RecordId");

                    b.ToTable("RecordRequests");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orcid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LogHub.Domain.Primitives.RecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Records");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Bases.Base", b =>
                {
                    b.HasBaseType("LogHub.Domain.Primitives.RecordEntity");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Bases", (string)null);
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlan", b =>
                {
                    b.HasBaseType("LogHub.Domain.Primitives.RecordEntity");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("OrganisationId");

                    b.ToTable("DataManagementPlans", (string)null);
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.Document", b =>
                {
                    b.HasBaseType("LogHub.Domain.Primitives.RecordEntity");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LogbookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasIndex("LogbookId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Logbooks.Logbook", b =>
                {
                    b.HasBaseType("LogHub.Domain.Primitives.RecordEntity");

                    b.Property<Guid>("BaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.HasIndex("BaseId");

                    b.ToTable("Logbooks", (string)null);
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Actions.RecordAction", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Primitives.RecordEntity", null)
                        .WithMany("Actions")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Bases.Label", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Bases.Base", null)
                        .WithMany("Labels")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.Question", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlan", null)
                        .WithMany("Questions")
                        .HasForeignKey("DataManagementPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.DocEditor", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Docs.Document", null)
                        .WithMany("Editors")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.DocLabel", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Docs.Document", null)
                        .WithMany("Labels")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.FavouriteDoc", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany("FavouritePages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Organisations.Department", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Organisations.Organisation", null)
                        .WithMany("Departments")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Permissions.Permission", b =>
                {
                    b.HasOne("LogHub.Domain.Primitives.RecordEntity", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Requests.RecordRequest", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Primitives.RecordEntity", null)
                        .WithMany("Requests")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Organisations.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("LogHub.Domain.Entities.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogHub.Domain.Entities.Users.UserSetting", "UserSetting", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AutoSave")
                                .HasColumnType("bit");

                            b1.Property<bool>("EmailNotification")
                                .HasColumnType("bit");

                            b1.Property<int>("FontSize")
                                .HasColumnType("int");

                            b1.Property<int>("Theme")
                                .HasColumnType("int");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("UserSetting")
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Bases.Base", b =>
                {
                    b.HasOne("LogHub.Domain.Primitives.RecordEntity", null)
                        .WithOne()
                        .HasForeignKey("LogHub.Domain.Entities.Bases.Base", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlan", b =>
                {
                    b.HasOne("LogHub.Domain.Primitives.RecordEntity", null)
                        .WithOne()
                        .HasForeignKey("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Organisations.Organisation", null)
                        .WithMany("DataManagementPlans")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.Document", b =>
                {
                    b.HasOne("LogHub.Domain.Primitives.RecordEntity", null)
                        .WithOne()
                        .HasForeignKey("LogHub.Domain.Entities.Docs.Document", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Entities.Logbooks.Logbook", null)
                        .WithMany()
                        .HasForeignKey("LogbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Logbooks.Logbook", b =>
                {
                    b.HasOne("LogHub.Domain.Entities.Bases.Base", null)
                        .WithMany()
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogHub.Domain.Primitives.RecordEntity", null)
                        .WithOne()
                        .HasForeignKey("LogHub.Domain.Entities.Logbooks.Logbook", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.Navigation("DataManagementPlans");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("FavouritePages");
                });

            modelBuilder.Entity("LogHub.Domain.Primitives.RecordEntity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Permissions");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Bases.Base", b =>
                {
                    b.Navigation("Labels");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.DataManagementPlans.DataManagementPlan", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LogHub.Domain.Entities.Docs.Document", b =>
                {
                    b.Navigation("Editors");

                    b.Navigation("Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
